### ISSUE TITLE
Add more OAuth Social Logins

### ISSUE THREAD

**Issue by samyak-jain** [samyak-jain/AgoraBackend#2]
Add Support for the following social logins using OAuth:
- [ ] Apple
- [ ] Microsoft
- [ ] Slack

In terms of scope of what is needed, the OAuth implementation would require only the name and email address of the user logging in. 

**Steps:**
- [ ] Make a PR
- [ ] Code review by a Maintainer. 
- [ ] Discussion and Implementation on any suggested changes
- [ ] Update Documentation if necessary

**Comment by samyak-jain** [comment]
The OAuth mechanism will be migrated to the following library: https://github.com/markbates/goth

**Comment by samyak-jain** [comment]
For Reference: the following file is responsible for the OAuth: https://github.com/samyak-jain/AgoraBackend/blob/master/routes/common.go
