### ISSUE TITLE
Make improvements to Logging infrastructure

### ISSUE THREAD

**Issue by samyak-jain** [samyak-jain/AgoraBackend#4]
**About:**
Tracking issues are used to record the overall progress of implementation. They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions. A tracking issue is however not meant for large scale discussion, questions, or bug reports about a feature. Instead, open a dedicated issue for the specific matter.

**Describe Feature being implemented.**
Add the following improvements to the logging infrastructure
- [ ] Add log rotation
- [ ] More control over the log levels
- [ ] Add more context in the logging
- [ ] Add Database logging using https://github.com/simukti/sqldb-logger

**Steps:**
- [ ] Make a PR
- [ ] Code review by a Maintainer. 
- [ ] Discussion and Implementation on any suggested changes
- [ ] Update Documentation if necessary

**Comment by samyak-jain** [comment]
Fixed In https://github.com/samyak-jain/AgoraBackend/tree/logging-improvement
